version: '3.1'

services:
  db:
    image: postgres:13-alpine
    container_name: db
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  app:
    build: .
    image: reactor-app:latest
    container_name: reactor-app
    ports:
      - "8888:8888"
      - "8050:8050"
      - "8051:8051"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
    depends_on:
      - db
      - mongo

networks:
  database:

volumes:
  data:
  mongo_data:
